{{
    config(
        tags=['wifeed']
    )
}}

with source as (
      select * from {{ source('wifeed', 'wifeed_bctc_chi_so_tai_chinh_doanh_nghiep_san_xuat_ttm_v2_raw') }}
),
renamed as (
    select
        {{ dbt_utils.generate_surrogate_key(["mack", "nam","type","quy"]) }} AS unique_id,
        {{ adapter.quote("mack") }},
        {{ adapter.quote("type") }},
        {{ adapter.quote("quy") }},
        {{ adapter.quote("nam") }},
        {{ adapter.quote("fcff") }},
        {{ adapter.quote("fcfe") }},
        {{ adapter.quote("ebit") }},
        {{ adapter.quote("ebitda") }},
        {{ adapter.quote("tylethuesuat") }},
        {{ adapter.quote("nopat") }},
        {{ adapter.quote("ccc") }},
        {{ adapter.quote("bienlaigop") }},
        {{ adapter.quote("bienlaisauthue") }},
        {{ adapter.quote("bienlaiebit") }},
        {{ adapter.quote("bienlaiebitda") }},
        {{ adapter.quote("bienlaitruocthue") }},
        {{ adapter.quote("vongquaytaisan") }},
        {{ adapter.quote("vongquayphaithu") }},
        {{ adapter.quote("vongquaytonkho") }},
        {{ adapter.quote("vongquayphaitra") }},
        {{ adapter.quote("roa") }},
        {{ adapter.quote("roe") }},
        {{ adapter.quote("roic") }},
        {{ adapter.quote("dongtien_hdkd_lnthuan") }},
        {{ adapter.quote("dongtien_hdkd_dtt") }},
        {{ adapter.quote("dongtien_hdkd_tts") }},
        {{ adapter.quote("dongtien_hdkd_vcsh") }},
        {{ adapter.quote("khtscd") }},
        {{ adapter.quote("capex") }},
        {{ adapter.quote("tt_dtt_yoy") }},
        {{ adapter.quote("tt_lng_yoy") }},
        {{ adapter.quote("tt_ebit_yoy") }},
        {{ adapter.quote("tt_ebitda_yoy") }},
        {{ adapter.quote("tt_lntt_yoy") }},
        {{ adapter.quote("tt_lnst_yoy") }},
        {{ adapter.quote("lnst_yoy") }},
        {{ adapter.quote("ln_hdkd_yoy") }},
        {{ adapter.quote("ln_hdtc_yoy") }},
        {{ adapter.quote("ln_ldlk_yoy") }},
        {{ adapter.quote("ln_khac_yoy") }},
        {{ adapter.quote("cpgiavon_yoy") }},
        {{ adapter.quote("cptaichinh_yoy") }},
        {{ adapter.quote("cpbh_yoy") }},
        {{ adapter.quote("cpqldn_yoy") }},
        {{ adapter.quote("lctt_hdkd_yoy") }},
        {{ adapter.quote("lctt_hddt_yoy") }},
        {{ adapter.quote("lctt_hdtc_yoy") }},
        {{ adapter.quote("lctt_trongky_yoy") }},
        {{ adapter.quote("khauhao_tscd_yoy") }},
        {{ adapter.quote("capex_yoy") }},
        {{ adapter.quote("dtt_qoq") }},
        {{ adapter.quote("ln_gop_qoq") }},
        {{ adapter.quote("ebit_qoq") }},
        {{ adapter.quote("ebitda_qoq") }},
        {{ adapter.quote("lntt_qoq") }},
        {{ adapter.quote("lnst_ctyme_qoq") }},
        {{ adapter.quote("lnst_qoq") }},
        {{ adapter.quote("ln_hdkd_qoq") }},
        {{ adapter.quote("ln_hdtc_qoq") }},
        {{ adapter.quote("ln_ldlk_qoq") }},
        {{ adapter.quote("ln_khac_qoq") }},
        {{ adapter.quote("cpgiavon_qoq") }},
        {{ adapter.quote("cptaichinh_qoq") }},
        {{ adapter.quote("cpbanhang_qoq") }},
        {{ adapter.quote("cpquanlydn_qoq") }},
        {{ adapter.quote("lctt_hdkd_qoq") }},
        {{ adapter.quote("lctt_hddt_qoq") }},
        {{ adapter.quote("lctt_hdtc_qoq") }},
        {{ adapter.quote("lctt_trongky_qoq") }},
        {{ adapter.quote("khauhao_tscd_qoq") }},
        {{ adapter.quote("capex_qoq") }},
        {{ adapter.quote("dol") }},
        {{ adapter.quote("dfl") }},
        {{ adapter.quote("dtl") }},
        {{ adapter.quote("ls_novay") }},
        {{ adapter.quote("novay_ebitda") }},
        {{ adapter.quote("novay_dongtienhdkd") }},
        {{ adapter.quote("ebit_laivay") }},
        {{ adapter.quote("dongtien_hdkd_novay") }},
        {{ adapter.quote("dongtien_hdkd_laivay") }},
        {{ adapter.quote("tile_chiphigiavon") }},
        {{ adapter.quote("tile_chiphilaivay") }},
        {{ adapter.quote("tile_chiphibanhang") }},
        {{ adapter.quote("tile_chiphiquanly") }},
        {{ adapter.quote("tile_loinhuanhoatdongkinhdoanhchinh") }},
        {{ adapter.quote("tile_loinhuantaichinh") }},
        {{ adapter.quote("tile_lailoldlk") }},
        {{ adapter.quote("tile_loinhuankhac") }},
        {{ adapter.quote("p_fcff") }},
        {{ adapter.quote("p_fcfe") }},
        {{ adapter.quote("lng_tmcp") }},
        {{ adapter.quote("p_gp") }},
        {{ adapter.quote("ev_ocf") }},
        {{ adapter.quote("ev_ebit") }},
        {{ adapter.quote("ev_ebitda") }},
        {{ adapter.quote("ev_fcff") }},
        {{ adapter.quote("ps") }},
        {{ adapter.quote("rev_per_share") }},
        {{ adapter.quote("lnst_ctyme") }},
        {{ adapter.quote("lnst_ctyme_yoy") }},
        {{ adapter.quote("lctt_hdkd") }},
        {{ adapter.quote("lctt_hddt") }},
        {{ adapter.quote("lctt_hdtc") }},
        {{ adapter.quote("lntt") }},
        {{ adapter.quote("lntt_yoy") }},
        {{ adapter.quote("lnst") }},
        {{ adapter.quote("eps") }},
        {{ adapter.quote("pe") }},
        {{ adapter.quote("ep") }},
        {{ adapter.quote("pe_dp") }},
        {{ adapter.quote("peg") }},
        {{ adapter.quote("peg_dc") }},
        {{ adapter.quote("graham_1") }},
        {{ adapter.quote("graham_2") }},
        {{ adapter.quote("graham_3") }},
        {{ adapter.quote("tl_chitracotucbangtien") }},
        {{ adapter.quote("dongtien_hdkd_tmcp") }},
        {{ adapter.quote("p_ocf") }},
        {{ adapter.quote("indexed_timestamp_") }},
        {{ adapter.quote("symbol_") }}

    from source
)
select * from renamed
  