{{
    config(
        tags=['wifeed']
    )
}}

with source as (
      select * from {{ source('wifeed', 'wifeed_bctc_ket_qua_kinh_doanh_chung_khoan_raw') }}
),
renamed as (
    select
        {{ dbt_utils.generate_surrogate_key(["code", "nam","type","quy"]) }} AS unique_id,
        {{ adapter.quote("code") }},
        {{ adapter.quote("type") }},
        {{ adapter.quote("quy") }},
        {{ adapter.quote("nam") }},
        {{ adapter.quote("donvikiemtoan") }},
        {{ adapter.quote("ykienkiemtoan") }},
        {{ adapter.quote("doanhthuhoatdong") }},
        {{ adapter.quote("laitucactaisantcfvtpl") }},
        {{ adapter.quote("laibantaisantcfvtpl") }},
        {{ adapter.quote("chenhlechtangvedglcacfvtpl") }},
        {{ adapter.quote("cotuctienlaiphatsinhtutaisantcfvtpl") }},
        {{ adapter.quote("laitucackhoandautunamgiudenngaydaohanhtm") }},
        {{ adapter.quote("laitucackhoanchovayvaphaithu") }},
        {{ adapter.quote("laitutaisantcsansangdebanafs") }},
        {{ adapter.quote("laitucaccongcuphatsinhphongnguaruiro") }},
        {{ adapter.quote("doanhthuhoatdongmoigioick") }},
        {{ adapter.quote("doanhthubaolanhdailyphathanhck") }},
        {{ adapter.quote("doanhthutuvandautuck") }},
        {{ adapter.quote("doanhthuhoatdonguythacdaugia") }},
        {{ adapter.quote("doanhthuhoatdongluukyck") }},
        {{ adapter.quote("doanhthuhoatdongtuvantc") }},
        {{ adapter.quote("doanhthuhoatdongkhac") }},
        {{ adapter.quote("cackhoangiamtrudoanhthu") }},
        {{ adapter.quote("cphoatdong") }},
        {{ adapter.quote("lotucactaisantcfvtpl") }},
        {{ adapter.quote("lotubancactaisantcfvtpl") }},
        {{ adapter.quote("chenhlechgiamdglcacfvtpl") }},
        {{ adapter.quote("cpgdmuacactaisantcfvtpl") }},
        {{ adapter.quote("locackhoandautunamgiudenngaydaohanhtm") }},
        {{ adapter.quote("cplaivaylotucackhoanchovayvaphaithu") }},
        {{ adapter.quote("lovachenhlechdgltaisanafskhiphanloailai") }},
        {{ adapter.quote("cpdphoannhaptstc") }},
        {{ adapter.quote("lotucactaisantcphaisinhphongnguaruiro") }},
        {{ adapter.quote("cphoatdongtudoanh") }},
        {{ adapter.quote("cphoatdongmoigioick") }},
        {{ adapter.quote("cphoatdongbaolanhdailyphathanhck") }},
        {{ adapter.quote("cphoatdongtuvandautuck") }},
        {{ adapter.quote("cphoatdongdaugiauythac") }},
        {{ adapter.quote("cpnghiepvuluukyck") }},
        {{ adapter.quote("cphoatdongtuvantc") }},
        {{ adapter.quote("cphoatdongkhac") }},
        {{ adapter.quote("lngop") }},
        {{ adapter.quote("doanhthuhoatdongtc") }},
        {{ adapter.quote("chenhlechlaitygiahoidoaidavachuathuchien") }},
        {{ adapter.quote("doanhthuduthucotuclaitienguikhongcodinh") }},
        {{ adapter.quote("laibanthanhlycackhoandautulkld") }},
        {{ adapter.quote("doanhthukhacvedautu") }},
        {{ adapter.quote("cptc") }},
        {{ adapter.quote("chenhlechlotygiahoidoaidavachuathuchien") }},
        {{ adapter.quote("cplaivay_pl") }},
        {{ adapter.quote("cpdpcackhoandaututcdaihan") }},
        {{ adapter.quote("cptckhac") }},
        {{ adapter.quote("lailotucongtyliendoanhlienket") }},
        {{ adapter.quote("cpbanhang") }},
        {{ adapter.quote("cpql") }},
        {{ adapter.quote("ketquahoatdongkd") }},
        {{ adapter.quote("lnkhac") }},
        {{ adapter.quote("thunhapkhac") }},
        {{ adapter.quote("cpkhac") }},
        {{ adapter.quote("tonglnketoantruocthue") }},
        {{ adapter.quote("lndathuchien_pl") }},
        {{ adapter.quote("lnchuathuchien_pl") }},
        {{ adapter.quote("cpthuetndn") }},
        {{ adapter.quote("cpthuetndnhienhanh") }},
        {{ adapter.quote("cpthuetndnhoanlai") }},
        {{ adapter.quote("lnsauthue") }},
        {{ adapter.quote("lnsauthuecuachusohuu") }},
        {{ adapter.quote("loiichcuacodongthieuso") }},
        {{ adapter.quote("lnsauthuephanbokhac") }},
        {{ adapter.quote("thunhaptoandienkhacsauthuetndn") }},
        {{ adapter.quote("lailotudanhgialaicackhoandautugiudenngaydaohan") }},
        {{ adapter.quote("lailotudanhgialaicactaisantcsansangdeban") }},
        {{ adapter.quote("lailotoandienkhacduocchiatuhoatdongdautuvaocongtycon") }},
        {{ adapter.quote("lailotudanhgialaicaccongcutcphaisinh") }},
        {{ adapter.quote("lailochenhlechtygiacuahoatdongtainuocngoai") }},
        {{ adapter.quote("lailotucackhoandautuvaocongtyconcongtylienketliendoanh") }},
        {{ adapter.quote("lailodanhgiacongcuphaisinh") }},
        {{ adapter.quote("lailodanhgialaitaisancodinhtheomohinhgiatrihoply") }},
        {{ adapter.quote("lailokhac") }},
        {{ adapter.quote("tongthunhaptoandien") }},
        {{ adapter.quote("tongthunhaptoandienphanbochocodongthieuso") }},
        {{ adapter.quote("tongthunhaptoandienphanbochovonchusohuu") }},
        {{ adapter.quote("laicobantrencophieu") }},
        {{ adapter.quote("thunhapphaloangtrencophieu") }},
        {{ adapter.quote("indexed_timestamp_") }},
        {{ adapter.quote("symbol_") }}

    from source
)
select * from renamed
  