{{
    config(
        tags=['wifeed']
    )
}}

with source as (
      select * from {{ source('wifeed', 'wifeed_bctc_chi_so_tai_chinh_ngan_hang_ttm_v2_raw') }}
),
renamed as (
    select
        {{ dbt_utils.generate_surrogate_key(["mack", "nam","type","quy"]) }} AS unique_id,
        {{ adapter.quote("mack") }},
        {{ adapter.quote("type") }},
        {{ adapter.quote("quy") }},
        {{ adapter.quote("nam") }},
        {{ adapter.quote("roa") }},
        {{ adapter.quote("roe") }},
        {{ adapter.quote("nim") }},
        {{ adapter.quote("cof") }},
        {{ adapter.quote("yea") }},
        {{ adapter.quote("cir") }},
        {{ adapter.quote("tt_thunhaplai_yoy") }},
        {{ adapter.quote("tt_chiphilai_yoy") }},
        {{ adapter.quote("tt_thunhaplaithuan_yoy") }},
        {{ adapter.quote("tt_lailotudichvu_yoy") }},
        {{ adapter.quote("tt_lailotungoaihoivavang_yoy") }},
        {{ adapter.quote("tt_lailomuabanckkd_yoy") }},
        {{ adapter.quote("tt_lailomubanckdt_yoy") }},
        {{ adapter.quote("tt_loinhuankhac_yoy") }},
        {{ adapter.quote("tt_thunhaptugopvonmuacophan_yoy") }},
        {{ adapter.quote("tt_tongthunhaphoatdong_yoy") }},
        {{ adapter.quote("tt_tongchiphihoatdong_yoy") }},
        {{ adapter.quote("tt_lntruocduphong_yoy") }},
        {{ adapter.quote("tt_chiphiduphong_yoy") }},
        {{ adapter.quote("tt_lntt_yoy") }},
        {{ adapter.quote("tt_lnst_yoy") }},
        {{ adapter.quote("tt_lnstme_yoy") }},
        {{ adapter.quote("tt_thunhaplai_qoq") }},
        {{ adapter.quote("tt_chiphilai_qoq") }},
        {{ adapter.quote("tt_thunhaplaithuan_qoq") }},
        {{ adapter.quote("tt_lailotudichvu_qoq") }},
        {{ adapter.quote("tt_lailotungoaihoivavang_qoq") }},
        {{ adapter.quote("tt_lailomuabanckkd_qoq") }},
        {{ adapter.quote("tt_lailomubanckdt_qoq") }},
        {{ adapter.quote("tt_loinhuankhac_qoq") }},
        {{ adapter.quote("tt_thunhaptugopvonmuacophan_qoq") }},
        {{ adapter.quote("tt_tongthunhaphoatdong_qoq") }},
        {{ adapter.quote("tt_tongchiphihoatdong_qoq") }},
        {{ adapter.quote("tt_lntruocduphong_qoq") }},
        {{ adapter.quote("tt_chiphiduphong_qoq") }},
        {{ adapter.quote("tt_lntt_qoq") }},
        {{ adapter.quote("tt_lnst_qoq") }},
        {{ adapter.quote("tt_lnstme_qoq") }},
        {{ adapter.quote("tile_thunhaplaithuan") }},
        {{ adapter.quote("tile_laithuantuhoatdongdichvu") }},
        {{ adapter.quote("tile_loinhuantuhoatdongthanhtoan") }},
        {{ adapter.quote("tile_loinhuantuhoatdongkinhdoanhbaohiem") }},
        {{ adapter.quote("tile_loinhuantudichvuchungkhoan") }},
        {{ adapter.quote("tile_loinhuantukinhdoanhvangvangoaihoi") }},
        {{ adapter.quote("tile_lailotumuabanckdt") }},
        {{ adapter.quote("tile_lailotumuabanckkd") }},
        {{ adapter.quote("tile_loinhuankhac") }},
        {{ adapter.quote("tile_thunhaptugopvonmuacophan") }},
        {{ adapter.quote("tile_chiphiduphong") }},
        {{ adapter.quote("tylethuesuat") }},
        {{ adapter.quote("dongtien_hdkd_lnthuan") }},
        {{ adapter.quote("dongtien_hdkd_tts") }},
        {{ adapter.quote("dongtien_hdkd_vcsh") }},
        {{ adapter.quote("lnst_ctyme") }},
        {{ adapter.quote("lnst_ctyme_yoy") }},
        {{ adapter.quote("lnst_ctyme_qoq") }},
        {{ adapter.quote("lctt_hdkd") }},
        {{ adapter.quote("lctt_hddt") }},
        {{ adapter.quote("lctt_hdtc") }},
        {{ adapter.quote("lntt") }},
        {{ adapter.quote("lntt_yoy") }},
        {{ adapter.quote("lntt_qoq") }},
        {{ adapter.quote("lnst") }},
        {{ adapter.quote("lnst_yoy") }},
        {{ adapter.quote("lnst_qoq") }},
        {{ adapter.quote("eps") }},
        {{ adapter.quote("pe") }},
        {{ adapter.quote("ep") }},
        {{ adapter.quote("pe_dp") }},
        {{ adapter.quote("peg") }},
        {{ adapter.quote("peg_dc") }},
        {{ adapter.quote("graham_1") }},
        {{ adapter.quote("graham_2") }},
        {{ adapter.quote("graham_3") }},
        {{ adapter.quote("tl_chitracotucbangtien") }},
        {{ adapter.quote("dongtien_hdkd_tmcp") }},
        {{ adapter.quote("p_ocf") }},
        {{ adapter.quote("indexed_timestamp_") }},
        {{ adapter.quote("symbol_") }}

    from source
)
select * from renamed
  