{{
    config(
        tags=['wifeed']
    )
}}

with source as (
      select * from {{ source('wifeed', 'wifeed_bctc_chi_so_tai_chinh_bao_hiem_ttm_v2_raw') }}
),
renamed as (
    select
        {{ dbt_utils.generate_surrogate_key(["mack", "nam","type","quy"]) }} AS unique_id,
        {{ adapter.quote("mack") }},
        {{ adapter.quote("type") }},
        {{ adapter.quote("quy") }},
        {{ adapter.quote("nam") }},
        {{ adapter.quote("tlbt_bhchayno") }},
        {{ adapter.quote("tlbt_bhnt") }},
        {{ adapter.quote("tlbt_bhpnt") }},
        {{ adapter.quote("tlbt_bhsk") }},
        {{ adapter.quote("tlbt_bhtauthuy") }},
        {{ adapter.quote("tlbt_bhtn") }},
        {{ adapter.quote("tlbt_bhtsvathiethai") }},
        {{ adapter.quote("tlbt_bhxecogioi") }},
        {{ adapter.quote("ttdthu_tm_baohiemhonhop_bhg") }},
        {{ adapter.quote("ttdthu_tm_baohiemkhac_bhg") }},
        {{ adapter.quote("ttdthu_tm_baohiemlienketchung_bhg") }},
        {{ adapter.quote("ttdthu_tm_bhchayno_bhg") }},
        {{ adapter.quote("ttdthu_tm_bhsuckhoe_bhg") }},
        {{ adapter.quote("ttdthu_tm_bhtaisanthiethai_bhg") }},
        {{ adapter.quote("ttdthu_tm_bhtauthuy_bhg") }},
        {{ adapter.quote("ttdthu_tm_bhtrachnhiem_bhg") }},
        {{ adapter.quote("ttdthu_tm_bhxecogioi_bhg") }},
        {{ adapter.quote("ttln_lailotucongtyliendoanhlienket") }},
        {{ adapter.quote("ttln_lngop") }},
        {{ adapter.quote("ttln_lnhdtaichinh") }},
        {{ adapter.quote("ttln_lnkhac") }},
        {{ adapter.quote("ttln_lntuhdkdkhac") }},
        {{ adapter.quote("tt_chiboithuongbaohiemgoc_yoy") }},
        {{ adapter.quote("tt_chiboithuongnhantaibaohiem_yoy") }},
        {{ adapter.quote("tt_chihoahongbaohiemgoc_yoy") }},
        {{ adapter.quote("tt_chiphibanhangbaohiemgoc_yoy") }},
        {{ adapter.quote("tt_chiphiquanlydn_yoy") }},
        {{ adapter.quote("tt_doanhthuphibaohiemthuan_yoy") }},
        {{ adapter.quote("tt_doanhthuthuan_yoy") }},
        {{ adapter.quote("tt_lailotucongtyliendoanhlienket_yoy") }},
        {{ adapter.quote("tt_lngop_yoy") }},
        {{ adapter.quote("tt_lnhdtaichinh_yoy") }},
        {{ adapter.quote("tt_lnkhac_yoy") }},
        {{ adapter.quote("tt_lntuhdkdkhac_yoy") }},
        {{ adapter.quote("tt_luuchuyentienthuantuhddautu_yoy") }},
        {{ adapter.quote("tt_luuchuyentienthuantuhdkd_yoy") }},
        {{ adapter.quote("tt_luuchuyentienthuantuhdtaichinh_yoy") }},
        {{ adapter.quote("tt_phibaohiemgoc_yoy") }},
        {{ adapter.quote("tt_phinhantaibaohiem_yoy") }},
        {{ adapter.quote("tt_phinhuongtaibaohiem_yoy") }},
        {{ adapter.quote("tt_tangduphongnghiepvubaohiemgoc_yoy") }},
        {{ adapter.quote("tt_thuhoahongnhuongtaibaohiem_yoy") }},
        {{ adapter.quote("tt_tm_baohiemnhantho_bh_yoy") }},
        {{ adapter.quote("tt_tm_baohiemnhantho_bhg_yoy") }},
        {{ adapter.quote("tt_tm_baohiemphinhantho_bh_yoy") }},
        {{ adapter.quote("tt_tm_baohiemphinhantho_bhg_yoy") }},
        {{ adapter.quote("tt_tm_bhchayno_bhg_yoy") }},
        {{ adapter.quote("tt_tm_bhchayno_cbt_yoy") }},
        {{ adapter.quote("tt_tm_bhsuckhoe_bhg_yoy") }},
        {{ adapter.quote("tt_tm_bhsuckhoe_cbt_yoy") }},
        {{ adapter.quote("tt_tm_bhtaisanthiethai_bhg_yoy") }},
        {{ adapter.quote("tt_tm_bhtaisanthiethai_cbt_yoy") }},
        {{ adapter.quote("tt_tm_bhtauthuy_bhg_yoy") }},
        {{ adapter.quote("tt_tm_bhtauthuy_cbt_yoy") }},
        {{ adapter.quote("tt_tm_bhtrachnhiem_bhg_yoy") }},
        {{ adapter.quote("tt_tm_bhtrachnhiem_cbt_yoy") }},
        {{ adapter.quote("tt_tm_bhxecogioi_bhg_yoy") }},
        {{ adapter.quote("tt_tm_bhxecogioi_cbt_yoy") }},
        {{ adapter.quote("tt_tongchiboithuong_yoy") }},
        {{ adapter.quote("tt_tongchiboithuongvatratienbaohiem_yoy") }},
        {{ adapter.quote("tt_tongchitructiephdkdbaohiem_yoy") }},
        {{ adapter.quote("tt_tonglnketoantruocthue_bs_yoy") }},
        {{ adapter.quote("tt_chiboithuongbaohiemgoc_qoq") }},
        {{ adapter.quote("tt_chiboithuongnhantaibaohiem_qoq") }},
        {{ adapter.quote("tt_chihoahongbaohiemgoc_qoq") }},
        {{ adapter.quote("tt_chiphibanhangbaohiemgoc_qoq") }},
        {{ adapter.quote("tt_chiphiquanlydn_qoq") }},
        {{ adapter.quote("tt_doanhthuphibaohiemthuan_qoq") }},
        {{ adapter.quote("tt_doanhthuthuan_qoq") }},
        {{ adapter.quote("tt_lailotucongtyliendoanhlienket_qoq") }},
        {{ adapter.quote("tt_lngop_qoq") }},
        {{ adapter.quote("tt_lnhdtaichinh_qoq") }},
        {{ adapter.quote("tt_lnkhac_qoq") }},
        {{ adapter.quote("tt_lntuhdkdkhac_qoq") }},
        {{ adapter.quote("tt_luuchuyentienthuantuhddautu_qoq") }},
        {{ adapter.quote("tt_luuchuyentienthuantuhdkd_qoq") }},
        {{ adapter.quote("tt_luuchuyentienthuantuhdtaichinh_qoq") }},
        {{ adapter.quote("tt_phibaohiemgoc_qoq") }},
        {{ adapter.quote("tt_phinhantaibaohiem_qoq") }},
        {{ adapter.quote("tt_phinhuongtaibaohiem_qoq") }},
        {{ adapter.quote("tt_tangduphongnghiepvubaohiemgoc_qoq") }},
        {{ adapter.quote("tt_thuhoahongnhuongtaibaohiem_qoq") }},
        {{ adapter.quote("tt_tm_baohiemnhantho_bh_qoq") }},
        {{ adapter.quote("tt_tm_baohiemnhantho_bhg_qoq") }},
        {{ adapter.quote("tt_tm_baohiemphinhantho_bh_qoq") }},
        {{ adapter.quote("tt_tm_baohiemphinhantho_bhg_qoq") }},
        {{ adapter.quote("tt_tm_bhchayno_bhg_qoq") }},
        {{ adapter.quote("tt_tm_bhchayno_cbt_qoq") }},
        {{ adapter.quote("tt_tm_bhsuckhoe_bhg_qoq") }},
        {{ adapter.quote("tt_tm_bhsuckhoe_cbt_qoq") }},
        {{ adapter.quote("tt_tm_bhtaisanthiethai_bhg_qoq") }},
        {{ adapter.quote("tt_tm_bhtaisanthiethai_cbt_qoq") }},
        {{ adapter.quote("tt_tm_bhtauthuy_bhg_qoq") }},
        {{ adapter.quote("tt_tm_bhtauthuy_cbt_qoq") }},
        {{ adapter.quote("tt_tm_bhtrachnhiem_bhg_qoq") }},
        {{ adapter.quote("tt_tm_bhtrachnhiem_cbt_qoq") }},
        {{ adapter.quote("tt_tm_bhxecogioi_bhg_qoq") }},
        {{ adapter.quote("tt_tm_bhxecogioi_cbt_qoq") }},
        {{ adapter.quote("tt_tongchiboithuong_qoq") }},
        {{ adapter.quote("tt_tongchiboithuongvatratienbaohiem_qoq") }},
        {{ adapter.quote("tt_tongchitructiephdkdbaohiem_qoq") }},
        {{ adapter.quote("tt_tonglnketoantruocthue_bs_qoq") }},
        {{ adapter.quote("tylethuesuat") }},
        {{ adapter.quote("roa") }},
        {{ adapter.quote("roe") }},
        {{ adapter.quote("dongtien_hdkd_lnthuan") }},
        {{ adapter.quote("dongtien_hdkd_tts") }},
        {{ adapter.quote("dongtien_hdkd_vcsh") }},
        {{ adapter.quote("lnst_ctyme") }},
        {{ adapter.quote("lnst_ctyme_yoy") }},
        {{ adapter.quote("lnst_ctyme_qoq") }},
        {{ adapter.quote("lctt_hdkd") }},
        {{ adapter.quote("lctt_hddt") }},
        {{ adapter.quote("lctt_hdtc") }},
        {{ adapter.quote("lntt") }},
        {{ adapter.quote("lntt_yoy") }},
        {{ adapter.quote("lntt_qoq") }},
        {{ adapter.quote("lnst") }},
        {{ adapter.quote("lnst_yoy") }},
        {{ adapter.quote("lnst_qoq") }},
        {{ adapter.quote("eps") }},
        {{ adapter.quote("pe") }},
        {{ adapter.quote("ep") }},
        {{ adapter.quote("pe_dp") }},
        {{ adapter.quote("peg") }},
        {{ adapter.quote("peg_dc") }},
        {{ adapter.quote("graham_1") }},
        {{ adapter.quote("graham_2") }},
        {{ adapter.quote("graham_3") }},
        {{ adapter.quote("tl_chitracotucbangtien") }},
        {{ adapter.quote("dongtien_hdkd_tmcp") }},
        {{ adapter.quote("p_ocf") }},
        {{ adapter.quote("indexed_timestamp_") }},
        {{ adapter.quote("symbol_") }}

    from source
)
select * from renamed
  