{{
    config(
        tags=['wifeed']
    )
}}

with source as (
      select * from {{ source('wifeed', 'wifeed_bctc_ket_qua_kinh_doanh_bao_hiem_raw') }}
),
renamed as (
    select
        {{ dbt_utils.generate_surrogate_key(["code", "nam","type","quy"]) }} AS unique_id,
        {{ adapter.quote("code") }},
        {{ adapter.quote("type") }},
        {{ adapter.quote("quy") }},
        {{ adapter.quote("nam") }},
        {{ adapter.quote("donvikiemtoan") }},
        {{ adapter.quote("ykienkiemtoan") }},
        {{ adapter.quote("doanhthuphibaohiem") }},
        {{ adapter.quote("phibaohiemgoc") }},
        {{ adapter.quote("phinhantaibaohiem") }},
        {{ adapter.quote("tgduphongphibaohiemgoc") }},
        {{ adapter.quote("phinhuongtaibaohiem") }},
        {{ adapter.quote("tongphinhuongtaibaohiem") }},
        {{ adapter.quote("tgduphongphinhuongtaibaohiem") }},
        {{ adapter.quote("cackhoangiamtrukhac") }},
        {{ adapter.quote("doanhthuphibaohiemthuan") }},
        {{ adapter.quote("hoahongnhuongtaibaohiem") }},
        {{ adapter.quote("thuhoahongnhuongtaibaohiem") }},
        {{ adapter.quote("thukhachdkdbaohiem") }},
        {{ adapter.quote("doanhthuthuan") }},
        {{ adapter.quote("chiboithuong") }},
        {{ adapter.quote("tongchiboithuong") }},
        {{ adapter.quote("chiboithuongbaohiemgoc") }},
        {{ adapter.quote("chiboithuongnhantaibaohiem") }},
        {{ adapter.quote("chiboithuongkhac") }},
        {{ adapter.quote("cackhoangiamtru") }},
        {{ adapter.quote("thudoinguoithuba") }},
        {{ adapter.quote("thuhangdaxulyboithuong100") }},
        {{ adapter.quote("cackhoangiamtrukhac_chibt") }},
        {{ adapter.quote("thuboithuongnhuongtaibaohiem") }},
        {{ adapter.quote("tangduphongnghiepvubaohiemgoc") }},
        {{ adapter.quote("tgduphongtoanhoc") }},
        {{ adapter.quote("tanggiamduphongcamketdaututoithieu") }},
        {{ adapter.quote("tanggiamduphongchialai") }},
        {{ adapter.quote("tanggiamduphongdambaocandoi") }},
        {{ adapter.quote("tanggiamduphongnghiepvubaohiemgockhac") }},
        {{ adapter.quote("tgduphongboithuongbaohiemgoc") }},
        {{ adapter.quote("tgduphongboithuongnhuongtaibaohiem") }},
        {{ adapter.quote("tongchiboithuongvatratienbaohiem") }},
        {{ adapter.quote("trichduphongdaodonglon") }},
        {{ adapter.quote("chikhachdkdbaohiemgoc") }},
        {{ adapter.quote("chihoahongbaohiemgoc") }},
        {{ adapter.quote("chidoinguoithu3") }},
        {{ adapter.quote("chixulyhangboithuong100") }},
        {{ adapter.quote("chidephonghanchetonthat") }},
        {{ adapter.quote("chigiamdinhchidanhgiaruirodoituongduocbaohiemchikhac") }},
        {{ adapter.quote("chiphibanhangbaohiemgoc") }},
        {{ adapter.quote("chikhachdbaohiemgoc") }},
        {{ adapter.quote("chikhachdkdnhantaibaohiem") }},
        {{ adapter.quote("chihdnhuongtaibaohiem") }},
        {{ adapter.quote("chikhachoatdongkinhdoanhbaohiem") }},
        {{ adapter.quote("tongchitructiephdkdbaohiem") }},
        {{ adapter.quote("lngop") }},
        {{ adapter.quote("lntuhdkdkhac") }},
        {{ adapter.quote("doanhthuhdkdkhac") }},
        {{ adapter.quote("cphdkdkhac") }},
        {{ adapter.quote("lnhdtaichinh") }},
        {{ adapter.quote("doanhthuhdtaichinh") }},
        {{ adapter.quote("chiphitaichinh") }},
        {{ adapter.quote("lailotucongtyliendoanhlienket") }},
        {{ adapter.quote("chiphiquanlydn") }},
        {{ adapter.quote("lnthuantuhdkd") }},
        {{ adapter.quote("lnkhac") }},
        {{ adapter.quote("thunhapkhac") }},
        {{ adapter.quote("chiphikhac") }},
        {{ adapter.quote("tonglnketoantruocthue_bs") }},
        {{ adapter.quote("chiphithuetndnhienhanh") }},
        {{ adapter.quote("chiphithuetndnhoanlai") }},
        {{ adapter.quote("lnstthunhapdn") }},
        {{ adapter.quote("loiichcuacodongthieuso") }},
        {{ adapter.quote("lnstcuacongtyme") }},
        {{ adapter.quote("laicobantrencophieu") }},
        {{ adapter.quote("indexed_timestamp_") }},
        {{ adapter.quote("symbol_") }}

    from source
)
select * from renamed
  