{{
    config(
        tags=['wifeed']
    )
}}

with source as (
      select * from {{ source('wifeed', 'wifeed_bctc_chi_so_tai_chinh_chung_khoan_ttm_v2_raw') }}
),
renamed as (
    select
        {{ dbt_utils.generate_surrogate_key(["mack", "nam","type","quy"]) }} AS unique_id,
        {{ adapter.quote("mack") }},
        {{ adapter.quote("type") }},
        {{ adapter.quote("quy") }},
        {{ adapter.quote("nam") }},
        {{ adapter.quote("dtnhdt") }},
        {{ adapter.quote("dtchovay") }},
        {{ adapter.quote("dtdanhgialaifvtpl") }},
        {{ adapter.quote("dtbantsfvtpl") }},
        {{ adapter.quote("dtfvtpl") }},
        {{ adapter.quote("dthtm") }},
        {{ adapter.quote("dtafs") }},
        {{ adapter.quote("dttudoanhvanguonvon") }},
        {{ adapter.quote("doanhthu") }},
        {{ adapter.quote("chiphinhdt") }},
        {{ adapter.quote("chiphihoatdong") }},
        {{ adapter.quote("laitudoanhnguonvonchovaykyquy") }},
        {{ adapter.quote("lainganhangdt") }},
        {{ adapter.quote("laimoigioi") }},
        {{ adapter.quote("laituvantaichinh") }},
        {{ adapter.quote("tile_cpdphoannhaptstc") }},
        {{ adapter.quote("tile_chiphitudoanh") }},
        {{ adapter.quote("tile_chiphimoigioi") }},
        {{ adapter.quote("tile_chiphibaolanh") }},
        {{ adapter.quote("tile_chiphidautuck") }},
        {{ adapter.quote("tile_chiphidaugia") }},
        {{ adapter.quote("tile_chiphiluuky") }},
        {{ adapter.quote("tile_chiphituvan") }},
        {{ adapter.quote("tile_chiphikhac") }},
        {{ adapter.quote("tile_nganhangdt") }},
        {{ adapter.quote("tile_dtchovay") }},
        {{ adapter.quote("tile_tudoanhnguonvon") }},
        {{ adapter.quote("tile_moigioichungkhoan") }},
        {{ adapter.quote("dtnhdt_yoy") }},
        {{ adapter.quote("dtchovay_yoy") }},
        {{ adapter.quote("dttudoanhvanguonvon_yoy") }},
        {{ adapter.quote("doanhthuhoatdongmoigioick_yoy") }},
        {{ adapter.quote("cpdphoannhaptstc_yoy") }},
        {{ adapter.quote("cphoatdongtudoanh_yoy") }},
        {{ adapter.quote("cphoatdongmoigioick_yoy") }},
        {{ adapter.quote("cphoatdongbaolanhdailyphathanhck_yoy") }},
        {{ adapter.quote("cphoatdongtuvandautuck_yoy") }},
        {{ adapter.quote("cphoatdongdaugiauythac_yoy") }},
        {{ adapter.quote("cpnghiepvuluukyck_yoy") }},
        {{ adapter.quote("cphoatdongtuvantc_yoy") }},
        {{ adapter.quote("cphoatdongkhac_yoy") }},
        {{ adapter.quote("tonglnketoantruocthue_yoy") }},
        {{ adapter.quote("lnsauthue_yoy") }},
        {{ adapter.quote("laitudoanhnguonvonchovaykyquy_yoy") }},
        {{ adapter.quote("lainganhangdt_yoy") }},
        {{ adapter.quote("laimoigioi_yoy") }},
        {{ adapter.quote("laituvantaichinh_yoy") }},
        {{ adapter.quote("doanhthu_qoq") }},
        {{ adapter.quote("dtnhdt_qoq") }},
        {{ adapter.quote("dtchovay_qoq") }},
        {{ adapter.quote("dttudoanhvanguonvon_qoq") }},
        {{ adapter.quote("doanhthuhoatdongmoigioick_qoq") }},
        {{ adapter.quote("chiphihoatdong_qoq") }},
        {{ adapter.quote("cpdphoannhaptstc_qoq") }},
        {{ adapter.quote("cphoatdongtudoanh_qoq") }},
        {{ adapter.quote("cphoatdongmoigioick_qoq") }},
        {{ adapter.quote("cphoatdongbaolanhdailyphathanhck_qoq") }},
        {{ adapter.quote("cphoatdongtuvandautuck_qoq") }},
        {{ adapter.quote("cphoatdongdaugiauythac_qoq") }},
        {{ adapter.quote("cpnghiepvuluukyck_qoq") }},
        {{ adapter.quote("cphoatdongtuvantc_qoq") }},
        {{ adapter.quote("cphoatdongkhac_qoq") }},
        {{ adapter.quote("tonglnketoantruocthue_qoq") }},
        {{ adapter.quote("lnsauthue_qoq") }},
        {{ adapter.quote("laitudoanhnguonvonchovaykyquy_qoq") }},
        {{ adapter.quote("lainganhangdt_qoq") }},
        {{ adapter.quote("laimoigioi_qoq") }},
        {{ adapter.quote("laituvantaichinh_qoq") }},
        {{ adapter.quote("loinhuanhoatdong") }},
        {{ adapter.quote("chiphihoatdong_yoy") }},
        {{ adapter.quote("laitucackhoanchovayvaphaithu_yoy") }},
        {{ adapter.quote("doanhthu_yoy") }},
        {{ adapter.quote("loinhuanhoatdong_yoy") }},
        {{ adapter.quote("tile_chovaymargin_qoq") }},
        {{ adapter.quote("tile_chovayungtrc_qoq") }},
        {{ adapter.quote("laitucackhoanchovayvaphaithu_qoq") }},
        {{ adapter.quote("loinhuanhoatdong_qoq") }},
        {{ adapter.quote("tylethuesuat") }},
        {{ adapter.quote("roa") }},
        {{ adapter.quote("roe") }},
        {{ adapter.quote("dongtien_hdkd_lnthuan") }},
        {{ adapter.quote("dongtien_hdkd_tts") }},
        {{ adapter.quote("dongtien_hdkd_vcsh") }},
        {{ adapter.quote("lnst_ctyme") }},
        {{ adapter.quote("lnst_ctyme_yoy") }},
        {{ adapter.quote("lnst_ctyme_qoq") }},
        {{ adapter.quote("lctt_hdkd") }},
        {{ adapter.quote("lctt_hddt") }},
        {{ adapter.quote("lctt_hdtc") }},
        {{ adapter.quote("lntt") }},
        {{ adapter.quote("lntt_yoy") }},
        {{ adapter.quote("lntt_qoq") }},
        {{ adapter.quote("lnst") }},
        {{ adapter.quote("lnst_yoy") }},
        {{ adapter.quote("lnst_qoq") }},
        {{ adapter.quote("eps") }},
        {{ adapter.quote("pe") }},
        {{ adapter.quote("ep") }},
        {{ adapter.quote("pe_dp") }},
        {{ adapter.quote("peg") }},
        {{ adapter.quote("peg_dc") }},
        {{ adapter.quote("graham_1") }},
        {{ adapter.quote("graham_2") }},
        {{ adapter.quote("graham_3") }},
        {{ adapter.quote("tl_chitracotucbangtien") }},
        {{ adapter.quote("dongtien_hdkd_tmcp") }},
        {{ adapter.quote("p_ocf") }},
        {{ adapter.quote("indexed_timestamp_") }},
        {{ adapter.quote("symbol_") }}

    from source
)
select * from renamed
  