schema:
  table_name: wifeed_bctc_chi_so_tai_chinh_bao_hiem_ttm_v2_raw
  columns:
    - name: mack
      type: text
    - name: type
      type: text
    - name: quy
      type: numeric
    - name: nam
      type: numeric
    - name: tlbt_bhchayno
      type: numeric
    - name: tlbt_bhnt
      type: numeric
    - name: tlbt_bhpnt
      type: numeric
    - name: tlbt_bhsk
      type: numeric
    - name: tlbt_bhtauthuy
      type: numeric
    - name: tlbt_bhtn
      type: numeric
    - name: tlbt_bhtsvathiethai
      type: numeric
    - name: tlbt_bhxecogioi
      type: numeric
    - name: ttdthu_tm_baohiemhonhop_bhg
      type: numeric
    - name: ttdthu_tm_baohiemkhac_bhg
      type: numeric
    - name: ttdthu_tm_baohiemlienketchung_bhg
      type: numeric
    - name: ttdthu_tm_bhchayno_bhg
      type: numeric
    - name: ttdthu_tm_bhsuckhoe_bhg
      type: numeric
    - name: ttdthu_tm_bhtaisanthiethai_bhg
      type: numeric
    - name: ttdthu_tm_bhtauthuy_bhg
      type: numeric
    - name: ttdthu_tm_bhtrachnhiem_bhg
      type: numeric
    - name: ttdthu_tm_bhxecogioi_bhg
      type: numeric
    - name: ttln_lailotucongtyliendoanhlienket
      type: numeric
    - name: ttln_lngop
      type: numeric
    - name: ttln_lnhdtaichinh
      type: numeric
    - name: ttln_lnkhac
      type: numeric
    - name: ttln_lntuhdkdkhac
      type: numeric
    - name: tt_chiboithuongbaohiemgoc_yoy
      type: numeric
    - name: tt_chiboithuongnhantaibaohiem_yoy
      type: numeric
    - name: tt_chihoahongbaohiemgoc_yoy
      type: numeric
    - name: tt_chiphibanhangbaohiemgoc_yoy
      type: numeric
    - name: tt_chiphiquanlydn_yoy
      type: numeric
    - name: tt_doanhthuphibaohiemthuan_yoy
      type: numeric
    - name: tt_doanhthuthuan_yoy
      type: numeric
    - name: tt_lailotucongtyliendoanhlienket_yoy
      type: numeric
    - name: tt_lngop_yoy
      type: numeric
    - name: tt_lnhdtaichinh_yoy
      type: numeric
    - name: tt_lnkhac_yoy
      type: numeric
    - name: tt_lntuhdkdkhac_yoy
      type: numeric
    - name: tt_luuchuyentienthuantuhddautu_yoy
      type: numeric
    - name: tt_luuchuyentienthuantuhdkd_yoy
      type: numeric
    - name: tt_luuchuyentienthuantuhdtaichinh_yoy
      type: numeric
    - name: tt_phibaohiemgoc_yoy
      type: numeric
    - name: tt_phinhantaibaohiem_yoy
      type: numeric
    - name: tt_phinhuongtaibaohiem_yoy
      type: numeric
    - name: tt_tangduphongnghiepvubaohiemgoc_yoy
      type: numeric
    - name: tt_thuhoahongnhuongtaibaohiem_yoy
      type: numeric
    - name: tt_tm_baohiemnhantho_bh_yoy
      type: numeric
    - name: tt_tm_baohiemnhantho_bhg_yoy
      type: numeric
    - name: tt_tm_baohiemphinhantho_bh_yoy
      type: numeric
    - name: tt_tm_baohiemphinhantho_bhg_yoy
      type: numeric
    - name: tt_tm_bhchayno_bhg_yoy
      type: numeric
    - name: tt_tm_bhchayno_cbt_yoy
      type: numeric
    - name: tt_tm_bhsuckhoe_bhg_yoy
      type: numeric
    - name: tt_tm_bhsuckhoe_cbt_yoy
      type: numeric
    - name: tt_tm_bhtaisanthiethai_bhg_yoy
      type: numeric
    - name: tt_tm_bhtaisanthiethai_cbt_yoy
      type: numeric
    - name: tt_tm_bhtauthuy_bhg_yoy
      type: numeric
    - name: tt_tm_bhtauthuy_cbt_yoy
      type: numeric
    - name: tt_tm_bhtrachnhiem_bhg_yoy
      type: numeric
    - name: tt_tm_bhtrachnhiem_cbt_yoy
      type: numeric
    - name: tt_tm_bhxecogioi_bhg_yoy
      type: numeric
    - name: tt_tm_bhxecogioi_cbt_yoy
      type: numeric
    - name: tt_tongchiboithuong_yoy
      type: numeric
    - name: tt_tongchiboithuongvatratienbaohiem_yoy
      type: numeric
    - name: tt_tongchitructiephdkdbaohiem_yoy
      type: numeric
    - name: tt_tonglnketoantruocthue_bs_yoy
      type: numeric
    - name: tt_chiboithuongbaohiemgoc_qoq
      type: numeric
    - name: tt_chiboithuongnhantaibaohiem_qoq
      type: numeric
    - name: tt_chihoahongbaohiemgoc_qoq
      type: numeric
    - name: tt_chiphibanhangbaohiemgoc_qoq
      type: numeric
    - name: tt_chiphiquanlydn_qoq
      type: numeric
    - name: tt_doanhthuphibaohiemthuan_qoq
      type: numeric
    - name: tt_doanhthuthuan_qoq
      type: numeric
    - name: tt_lailotucongtyliendoanhlienket_qoq
      type: numeric
    - name: tt_lngop_qoq
      type: numeric
    - name: tt_lnhdtaichinh_qoq
      type: numeric
    - name: tt_lnkhac_qoq
      type: numeric
    - name: tt_lntuhdkdkhac_qoq
      type: numeric
    - name: tt_luuchuyentienthuantuhddautu_qoq
      type: numeric
    - name: tt_luuchuyentienthuantuhdkd_qoq
      type: numeric
    - name: tt_luuchuyentienthuantuhdtaichinh_qoq
      type: numeric
    - name: tt_phibaohiemgoc_qoq
      type: numeric
    - name: tt_phinhantaibaohiem_qoq
      type: numeric
    - name: tt_phinhuongtaibaohiem_qoq
      type: numeric
    - name: tt_tangduphongnghiepvubaohiemgoc_qoq
      type: numeric
    - name: tt_thuhoahongnhuongtaibaohiem_qoq
      type: numeric
    - name: tt_tm_baohiemnhantho_bh_qoq
      type: numeric
    - name: tt_tm_baohiemnhantho_bhg_qoq
      type: numeric
    - name: tt_tm_baohiemphinhantho_bh_qoq
      type: numeric
    - name: tt_tm_baohiemphinhantho_bhg_qoq
      type: numeric
    - name: tt_tm_bhchayno_bhg_qoq
      type: numeric
    - name: tt_tm_bhchayno_cbt_qoq
      type: numeric
    - name: tt_tm_bhsuckhoe_bhg_qoq
      type: numeric
    - name: tt_tm_bhsuckhoe_cbt_qoq
      type: numeric
    - name: tt_tm_bhtaisanthiethai_bhg_qoq
      type: numeric
    - name: tt_tm_bhtaisanthiethai_cbt_qoq
      type: numeric
    - name: tt_tm_bhtauthuy_bhg_qoq
      type: numeric
    - name: tt_tm_bhtauthuy_cbt_qoq
      type: numeric
    - name: tt_tm_bhtrachnhiem_bhg_qoq
      type: numeric
    - name: tt_tm_bhtrachnhiem_cbt_qoq
      type: numeric
    - name: tt_tm_bhxecogioi_bhg_qoq
      type: numeric
    - name: tt_tm_bhxecogioi_cbt_qoq
      type: numeric
    - name: tt_tongchiboithuong_qoq
      type: numeric
    - name: tt_tongchiboithuongvatratienbaohiem_qoq
      type: numeric
    - name: tt_tongchitructiephdkdbaohiem_qoq
      type: numeric
    - name: tt_tonglnketoantruocthue_bs_qoq
      type: numeric
    - name: tylethuesuat
      type: numeric
    - name: roa
      type: numeric
    - name: roe
      type: numeric
    - name: dongtien_hdkd_lnthuan
      type: numeric
    - name: dongtien_hdkd_tts
      type: numeric
    - name: dongtien_hdkd_vcsh
      type: numeric
    - name: lnst_ctyme
      type: numeric
    - name: lnst_ctyme_yoy
      type: numeric
    - name: lnst_ctyme_qoq
      type: numeric
    - name: lctt_hdkd
      type: numeric
    - name: lctt_hddt
      type: numeric
    - name: lctt_hdtc
      type: numeric
    - name: lntt
      type: numeric
    - name: lntt_yoy
      type: numeric
    - name: lntt_qoq
      type: numeric
    - name: lnst
      type: numeric
    - name: lnst_yoy
      type: numeric
    - name: lnst_qoq
      type: numeric
    - name: eps
      type: numeric
    - name: pe
      type: numeric
    - name: ep
      type: numeric
    - name: pe_dp
      type: numeric
    - name: peg
      type: numeric
    - name: peg_dc
      type: numeric
    - name: graham_1
      type: numeric
    - name: graham_2
      type: numeric
    - name: graham_3
      type: numeric
    - name: tl_chitracotucbangtien
      type: numeric
    - name: dongtien_hdkd_tmcp
      type: numeric
    - name: p_ocf
      type: numeric
  primary:
    - mack
    - type
    - quy
    - nam
