schema:
  table_name: wifeed_bctc_chi_so_tai_chinh_ngan_hang_ttm_v2_raw
  columns:
    - name: mack
      type: text
    - name: type
      type: text
    - name: quy
      type: numeric
    - name: nam
      type: numeric
    - name: roa
      type: numeric
    - name: roe
      type: numeric
    - name: nim
      type: numeric
    - name: cof
      type: numeric
    - name: yea
      type: numeric
    - name: cir
      type: numeric
    - name: tt_thunhaplai_yoy
      type: numeric
    - name: tt_chiphilai_yoy
      type: numeric
    - name: tt_thunhaplaithuan_yoy
      type: numeric
    - name: tt_lailotudichvu_yoy
      type: numeric
    - name: tt_lailotungoaihoivavang_yoy
      type: numeric
    - name: tt_lailomuabanckkd_yoy
      type: numeric
    - name: tt_lailomubanckdt_yoy
      type: numeric
    - name: tt_loinhuankhac_yoy
      type: numeric
    - name: tt_thunhaptugopvonmuacophan_yoy
      type: numeric
    - name: tt_tongthunhaphoatdong_yoy
      type: numeric
    - name: tt_tongchiphihoatdong_yoy
      type: numeric
    - name: tt_lntruocduphong_yoy
      type: numeric
    - name: tt_chiphiduphong_yoy
      type: numeric
    - name: tt_lntt_yoy
      type: numeric
    - name: tt_lnst_yoy
      type: numeric
    - name: tt_lnstme_yoy
      type: numeric
    - name: tt_thunhaplai_qoq
      type: numeric
    - name: tt_chiphilai_qoq
      type: numeric
    - name: tt_thunhaplaithuan_qoq
      type: numeric
    - name: tt_lailotudichvu_qoq
      type: numeric
    - name: tt_lailotungoaihoivavang_qoq
      type: numeric
    - name: tt_lailomuabanckkd_qoq
      type: numeric
    - name: tt_lailomubanckdt_qoq
      type: numeric
    - name: tt_loinhuankhac_qoq
      type: numeric
    - name: tt_thunhaptugopvonmuacophan_qoq
      type: numeric
    - name: tt_tongthunhaphoatdong_qoq
      type: numeric
    - name: tt_tongchiphihoatdong_qoq
      type: numeric
    - name: tt_lntruocduphong_qoq
      type: numeric
    - name: tt_chiphiduphong_qoq
      type: numeric
    - name: tt_lntt_qoq
      type: numeric
    - name: tt_lnst_qoq
      type: numeric
    - name: tt_lnstme_qoq
      type: numeric
    - name: tile_thunhaplaithuan
      type: numeric
    - name: tile_laithuantuhoatdongdichvu
      type: numeric
    - name: tile_loinhuantuhoatdongthanhtoan
      type: numeric
    - name: tile_loinhuantuhoatdongkinhdoanhbaohiem
      type: numeric
    - name: tile_loinhuantudichvuchungkhoan
      type: numeric
    - name: tile_loinhuantukinhdoanhvangvangoaihoi
      type: numeric
    - name: tile_lailotumuabanckdt
      type: numeric
    - name: tile_lailotumuabanckkd
      type: numeric
    - name: tile_loinhuankhac
      type: numeric
    - name: tile_thunhaptugopvonmuacophan
      type: numeric
    - name: tile_chiphiduphong
      type: numeric
    - name: tylethuesuat
      type: numeric
    - name: dongtien_hdkd_lnthuan
      type: numeric
    - name: dongtien_hdkd_tts
      type: numeric
    - name: dongtien_hdkd_vcsh
      type: numeric
    - name: lnst_ctyme
      type: numeric
    - name: lnst_ctyme_yoy
      type: numeric
    - name: lnst_ctyme_qoq
      type: numeric
    - name: lctt_hdkd
      type: numeric
    - name: lctt_hddt
      type: numeric
    - name: lctt_hdtc
      type: numeric
    - name: lntt
      type: numeric
    - name: lntt_yoy
      type: numeric
    - name: lntt_qoq
      type: numeric
    - name: lnst
      type: numeric
    - name: lnst_yoy
      type: numeric
    - name: lnst_qoq
      type: numeric
    - name: eps
      type: numeric
    - name: pe
      type: numeric
    - name: ep
      type: numeric
    - name: pe_dp
      type: numeric
    - name: peg
      type: numeric
    - name: peg_dc
      type: numeric
    - name: graham_1
      type: numeric
    - name: graham_2
      type: numeric
    - name: graham_3
      type: numeric
    - name: tl_chitracotucbangtien
      type: numeric
    - name: dongtien_hdkd_tmcp
      type: numeric
    - name: p_ocf
      type: numeric
  primary:
    - mack
    - type
    - quy
    - nam
