schema:
  table_name: wifeed_bctc_chi_so_tai_chinh_chung_khoan_quarter_v2_raw
  columns:
    - name: mack
      type: text
    - name: type
      type: text
    - name: quy
      type: numeric
    - name: nam
      type: numeric
    - name: tilechovaykq
      type: numeric
    - name: tsquanlytheocamket
      type: numeric
    - name: dtnhdt
      type: numeric
    - name: dtchovay
      type: numeric
    - name: dtdanhgialaifvtpl
      type: numeric
    - name: dtbantsfvtpl
      type: numeric
    - name: dtfvtpl
      type: numeric
    - name: dthtm
      type: numeric
    - name: dtafs
      type: numeric
    - name: dttudoanhvanguonvon
      type: numeric
    - name: doanhthu
      type: numeric
    - name: chiphinhdt
      type: numeric
    - name: chiphihoatdong
      type: numeric
    - name: laitudoanhnguonvonchovaykyquy
      type: numeric
    - name: lainganhangdt
      type: numeric
    - name: laimoigioi
      type: numeric
    - name: laituvantaichinh
      type: numeric
    - name: tile_cpdphoannhaptstc
      type: numeric
    - name: tile_chiphitudoanh
      type: numeric
    - name: tile_chiphimoigioi
      type: numeric
    - name: tile_chiphibaolanh
      type: numeric
    - name: tile_chiphidautuck
      type: numeric
    - name: tile_chiphidaugia
      type: numeric
    - name: tile_chiphiluuky
      type: numeric
    - name: tile_chiphituvan
      type: numeric
    - name: tile_chiphikhac
      type: numeric
    - name: tile_nganhangdt
      type: numeric
    - name: tile_dtchovay
      type: numeric
    - name: tile_tudoanhnguonvon
      type: numeric
    - name: tile_moigioichungkhoan
      type: numeric
    - name: tile_cpniemyet
      type: numeric
    - name: tile_cpchuaniemyet
      type: numeric
    - name: tile_chungchiquy
      type: numeric
    - name: tile_traiphieu
      type: numeric
    - name: tile_tiengui
      type: numeric
    - name: tongcongtaisan_yoy
      type: numeric
    - name: taisantcnganhan_yoy
      type: numeric
    - name: tienvacackhoantuongduongtien_yoy
      type: numeric
    - name: taisantcfvtpl_yoy
      type: numeric
    - name: dautugiudenngaydaohanhtm_yoy
      type: numeric
    - name: cackhoanchovay_yoy
      type: numeric
    - name: cackhoantcsansangdebanafs_yoy
      type: numeric
    - name: dpsuygiamtaisantc_yoy
      type: numeric
    - name: tongcackhoanphaithunganhan_yoy
      type: numeric
    - name: phaithucacdichvuctckcungcap_yoy
      type: numeric
    - name: tratruocchonguoiban_yoy
      type: numeric
    - name: cackhoanphaithukhac_yoy
      type: numeric
    - name: taisannganhankhac_tong_yoy
      type: numeric
    - name: taisantcdaihan_yoy
      type: numeric
    - name: nonganhan_yoy
      type: numeric
    - name: vayvanothuetcnganhan_yoy
      type: numeric
    - name: traiphieuphathanhnganhan_yoy
      type: numeric
    - name: nguoimuatratientruocnganhan_yoy
      type: numeric
    - name: phaitrahoatdonggiaodichchungkhoan_yoy
      type: numeric
    - name: cpphaitranganhan_yoy
      type: numeric
    - name: nodaihan_yoy
      type: numeric
    - name: traiphieuphathanhdaihan_yoy
      type: numeric
    - name: vonchusohuu_tong_yoy
      type: numeric
    - name: vongopcuachusohuu_yoy
      type: numeric
    - name: tm_tienguicuandt_yoy
      type: numeric
    - name: tm_taisantcniemyetdangkygdtaivsdcuactck_yoy
      type: numeric
    - name: tm_taisantcdaluukytaivsdvachuagdcuactck_yoy
      type: numeric
    - name: tm_taisantcchovecuactck_yoy
      type: numeric
    - name: tm_taisantcchualuukytaivsdcuactck_yoy
      type: numeric
    - name: tsquanlytheocamket_yoy
      type: numeric
    - name: tm_phaitrandtvetienguigdcknhtmql_yoy
      type: numeric
    - name: tm_cophieuniemyetfvtplhoply_yoy
      type: numeric
    - name: tm_cophieuchuaniemyetfvtplhoply_yoy
      type: numeric
    - name: tm_chungchiquyfvtplhoply_yoy
      type: numeric
    - name: tm_traiphieufvtplhoply_yoy
      type: numeric
    - name: tm_taisantckhacfvtplhoply_yoy
      type: numeric
    - name: dtnhdt_yoy
      type: numeric
    - name: dtchovay_yoy
      type: numeric
    - name: dttudoanhvanguonvon_yoy
      type: numeric
    - name: doanhthuhoatdongmoigioick_yoy
      type: numeric
    - name: cpdphoannhaptstc_yoy
      type: numeric
    - name: cphoatdongtudoanh_yoy
      type: numeric
    - name: cphoatdongmoigioick_yoy
      type: numeric
    - name: cphoatdongbaolanhdailyphathanhck_yoy
      type: numeric
    - name: cphoatdongtuvandautuck_yoy
      type: numeric
    - name: cphoatdongdaugiauythac_yoy
      type: numeric
    - name: cpnghiepvuluukyck_yoy
      type: numeric
    - name: cphoatdongtuvantc_yoy
      type: numeric
    - name: cphoatdongkhac_yoy
      type: numeric
    - name: tonglnketoantruocthue_yoy
      type: numeric
    - name: lnsauthue_yoy
      type: numeric
    - name: laitudoanhnguonvonchovaykyquy_yoy
      type: numeric
    - name: lainganhangdt_yoy
      type: numeric
    - name: laimoigioi_yoy
      type: numeric
    - name: laituvantaichinh_yoy
      type: numeric
    - name: tm_chovaynghiepvukyquymargin_yoy
      type: numeric
    - name: tm_chovayungtruoctienbanckcuakhachhang_yoy
      type: numeric
    - name: doanhthu_qoq
      type: numeric
    - name: dtnhdt_qoq
      type: numeric
    - name: dtchovay_qoq
      type: numeric
    - name: dttudoanhvanguonvon_qoq
      type: numeric
    - name: doanhthuhoatdongmoigioick_qoq
      type: numeric
    - name: chiphihoatdong_qoq
      type: numeric
    - name: cpdphoannhaptstc_qoq
      type: numeric
    - name: cphoatdongtudoanh_qoq
      type: numeric
    - name: cphoatdongmoigioick_qoq
      type: numeric
    - name: cphoatdongbaolanhdailyphathanhck_qoq
      type: numeric
    - name: cphoatdongtuvandautuck_qoq
      type: numeric
    - name: cphoatdongdaugiauythac_qoq
      type: numeric
    - name: cpnghiepvuluukyck_qoq
      type: numeric
    - name: cphoatdongtuvantc_qoq
      type: numeric
    - name: cphoatdongkhac_qoq
      type: numeric
    - name: tonglnketoantruocthue_qoq
      type: numeric
    - name: lnsauthue_qoq
      type: numeric
    - name: laitudoanhnguonvonchovaykyquy_qoq
      type: numeric
    - name: lainganhangdt_qoq
      type: numeric
    - name: laimoigioi_qoq
      type: numeric
    - name: laituvantaichinh_qoq
      type: numeric
    - name: tongcongtaisan_qoq
      type: numeric
    - name: taisantcnganhan_qoq
      type: numeric
    - name: tienvacackhoantuongduongtien_qoq
      type: numeric
    - name: taisantcfvtpl_qoq
      type: numeric
    - name: dautugiudenngaydaohanhtm_qoq
      type: numeric
    - name: cackhoanchovay_qoq
      type: numeric
    - name: cackhoantcsansangdebanafs_qoq
      type: numeric
    - name: dpsuygiamtaisantc_qoq
      type: numeric
    - name: tongcackhoanphaithunganhan_qoq
      type: numeric
    - name: phaithucacdichvuctckcungcap_qoq
      type: numeric
    - name: tratruocchonguoiban_qoq
      type: numeric
    - name: cackhoanphaithukhac_qoq
      type: numeric
    - name: taisannganhankhac_tong_qoq
      type: numeric
    - name: taisantcdaihan_qoq
      type: numeric
    - name: nonganhan_qoq
      type: numeric
    - name: vayvanothuetcnganhan_qoq
      type: numeric
    - name: traiphieuphathanhnganhan_qoq
      type: numeric
    - name: nguoimuatratientruocnganhan_qoq
      type: numeric
    - name: phaitrahoatdonggiaodichchungkhoan_qoq
      type: numeric
    - name: cpphaitranganhan_qoq
      type: numeric
    - name: nodaihan_qoq
      type: numeric
    - name: traiphieuphathanhdaihan_qoq
      type: numeric
    - name: vonchusohuu_tong_qoq
      type: numeric
    - name: vongopcuachusohuu_qoq
      type: numeric
    - name: tm_tienguicuandt_qoq
      type: numeric
    - name: tm_taisantcniemyetdangkygdtaivsdcuactck_qoq
      type: numeric
    - name: tm_taisantcdaluukytaivsdvachuagdcuactck_qoq
      type: numeric
    - name: tm_taisantcchovecuactck_qoq
      type: numeric
    - name: tm_taisantcchualuukytaivsdcuactck_qoq
      type: numeric
    - name: tsquanlytheocamket_qoq
      type: numeric
    - name: tm_phaitrandtvetienguigdcknhtmql_qoq
      type: numeric
    - name: tm_cophieuniemyetfvtplhoply_qoq
      type: numeric
    - name: tm_cophieuchuaniemyetfvtplhoply_qoq
      type: numeric
    - name: tm_chungchiquyfvtplhoply_qoq
      type: numeric
    - name: tm_traiphieufvtplhoply_qoq
      type: numeric
    - name: tm_taisantckhacfvtplhoply_qoq
      type: numeric
    - name: tile_tien
      type: numeric
    - name: tile_fvtpl
      type: numeric
    - name: tile_htm
      type: numeric
    - name: tile_afs
      type: numeric
    - name: tile_chovay
      type: numeric
    - name: tile_phaithudichvu
      type: numeric
    - name: loinhuanhoatdong
      type: numeric
    - name: tstccuactckndt
      type: numeric
    - name: chiphihoatdong_yoy
      type: numeric
    - name: laitucackhoanchovayvaphaithu_yoy
      type: numeric
    - name: doanhthu_yoy
      type: numeric
    - name: loinhuanhoatdong_yoy
      type: numeric
    - name: tm_taisantcchovecuandt_yoy
      type: numeric
    - name: tm_taisantcchualuukytaivsdcuandt_yoy
      type: numeric
    - name: tstccuactckndt_yoy
      type: numeric
    - name: tm_taisantcdaluukyvsdchuagdcuandt_yoy
      type: numeric
    - name: tm_taisantcniemyetdangkygdtaivsd_yoy
      type: numeric
    - name: tile_chovaymargin_qoq
      type: numeric
    - name: tile_chovayungtrc_qoq
      type: numeric
    - name: laitucackhoanchovayvaphaithu_qoq
      type: numeric
    - name: loinhuanhoatdong_qoq
      type: numeric
    - name: tm_taisantcchovecuandt_qoq
      type: numeric
    - name: tm_taisantcchualuukytaivsdcuandt_qoq
      type: numeric
    - name: tstccuactckndt_qoq
      type: numeric
    - name: tm_taisantcdaluukyvsdchuagdcuandt_qoq
      type: numeric
    - name: tm_taisantcniemyetdangkygdtaivsd_qoq
      type: numeric
    - name: tile_phaithukhac
      type: numeric
    - name: tylethuesuat
      type: numeric
    - name: tongno_tongtaisan
      type: numeric
    - name: tts_vonchu
      type: numeric
    - name: vcsh_nguonvon
      type: numeric
    - name: nophaitra_vcsh
      type: numeric
    - name: lnst_ctyme
      type: numeric
    - name: lnst_ctyme_yoy
      type: numeric
    - name: lnst_ctyme_qoq
      type: numeric
    - name: vcsh
      type: numeric
    - name: vcsh_yoy
      type: numeric
    - name: vcsh_qoq
      type: numeric
    - name: lctt_hdkd
      type: numeric
    - name: lctt_hddt
      type: numeric
    - name: lctt_hdtc
      type: numeric
    - name: lntt
      type: numeric
    - name: lntt_yoy
      type: numeric
    - name: lntt_qoq
      type: numeric
    - name: nophaitra
      type: numeric
    - name: nophaitra_yoy
      type: numeric
    - name: nophaitra_qoq
      type: numeric
    - name: tts
      type: numeric
    - name: tts_yoy
      type: numeric
    - name: tts_qoq
      type: numeric
    - name: lnst
      type: numeric
    - name: lnst_yoy
      type: numeric
    - name: lnst_qoq
      type: numeric
    - name: vonhoa
      type: numeric
    - name: bookvalue
      type: numeric
    - name: bvps
      type: numeric
    - name: pb
      type: numeric
  primary:
    - mack
    - type
    - quy
    - nam
